### ISSUE TITLE
get_outputs_from_address does not properly append buffer for response greater than 989 bytes

### ISSUE THREAD

**Issue by osobiehl** [iotaledger/iota.c#138] opened 2021-07-20 11:56 UTC
## Bug description

Receiving more than 989 bytes from get_outputs_from_address does not properly append the rest of the response data, resulting in CJSON parsing failing due to truncated input.

## Version

Which version of the library are you running?
- Version:0.2.0

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL: api.hornet-0.testnet.chrysalis2.com
- Network: chrysalis / testnet

## Hardware specification

What hardware are you using?

- Operating system: Zephyr OS
- RAM:
- Number of cores: 1
- Device type: NRF9160 microcontroller
## Compiler and build tool specification
west
What compiler are you using?
GNU 10.2.0
What build tool are you using? 
CMake

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. call get_outputs from an address with several outputs. I used: "fc4a531cf8045e0300261db10d41fbfd832496cbc6b593ce905e9576d2dad8ef" 
2. receive an error return value due to CJSON parse failing
3. 

## Expected behaviour

Outputs are properly returned

## Actual behaviour

Outputs are only properly returned when total number of bytes from the node's response is less than 989 bytes
## Errors
no errors are reported by the terminal but I saw that the error propagates from a truncated string in http_client_get, here is an image of the debug log on a uart terminal (note I added a bunch of printf debug statements to try to track down the issue).

![image](https://user-images.githubusercontent.com/58215398/126319504-fd064061-8014-4688-ba53-eb6c372529e4.png)

the library acknowledges 1163 bytes were received but only processes 989 . . . .

(also sorry if this is fixed by simply changing something in the proj.conf file)

**Comment by oopsmonk** [comment] 2021-07-20 12:59
I assume you were using `zephyr-client-sdk`, did you try to increase the HTTP client buffer, `IOTA_HTTP_RECV_BUFF_SIZE` default is 1024?

**Comment by osobiehl** [comment] 2021-07-20 13:40
yes, I am using `zephyr-client-sdk` I increased `IOTA_HTTP_RECV_BUFF_SIZE` to 4096 but the same problem occurs

**Comment by oopsmonk** [comment] 2021-07-21 04:13
okay, the body length from the response is 5493 bytes which it has 75 output IDs. 
From the screenshot, the `net_http` didn't receive the response correctly, 989 bytes only. the connection was closed when `net_http` was waiting for more data coming.
the problem might be in `net_http`, need more info about why the connection is closed to define the root cause.

**Comment by oopsmonk** [comment] 2021-07-23 08:35
@osobiehl this problem doesn't appear on other platforms. I'm closing this issue and create https://github.com/iotaledger/zephyr-client-sdk/issues/2 for future investigation. 
feel free to reopen it if you think there is still a problem with this library.

**Closed as completed by oopsmonk** 2021-07-23 08:35 UTC
Labels: Type: Bug
