### ISSUE TITLE
'iota_client_find_transaction_objects' may fail when the number of return transaction objects is huge

### ISSUE THREAD

**Issue by howjmay** [iotaledger/iota.c#47] opened 2020-09-07 07:51 UTC
## Bug description

`iota_client_find_transaction_objects` may meet JSON parsing failed when the return transaction number is huge.

## Version

Which version of the library are you running?

- Version: commit `3f1c255bd6e7ccc19bd527a83fa4593d342cad32`

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL:
- Network:

## Hardware specification

What hardware are you using?

- Operating system:
- RAM:
- Number of cores:
- Device type:
## Compiler and build tool specification

What compiler are you using?

What build tool are you using? 
Bazel

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

## Expected behaviour

Parsing the JSON response successfully.

## Actual behaviour

Failed to parse the object.

## Errors
```
[0;37;40m2020-09-07 07:39:41:cclient_extended:  DEBUG: [0m[1;3;32;40m[iota_client_find_transaction_objects:20][0m
[0;37;40m2020-09-07 07:39:41:   cclient_core:  DEBUG: [0m[1;3;32;40m[iota_client_find_transactions:14][0m
[0;37;40m2020-09-07 07:39:41:json_serializer:  DEBUG: [0m[1;3;32;40m[json_find_transactions_serialize_request:14][0m
[0;37;40m2020-09-07 07:39:41:json_serializer:  DEBUG: [0m[1;3;32;40m[json_find_transactions_deserialize_response:161] {"hashes":["YUSKMJNDJSPP9FDFQNZPDEZGTHGTKOE9FKRFJTTHEPAEMOTCAZHWZKAJQGKVKCQK9SVX9ILRJRLYZ9999","AUPHNHIOVNFBGUIPWCMNICKH99EUDFWNMJMBIUGZDBRLIOTWPWAMCAYMUTETDSTUWORR9HBSNCEB99999","EWPODWXUMZGXRESCCNLE... [0m
[0;37;40m2020-09-07 07:39:41:   cclient_core:  DEBUG: [0m[1;3;32;40m[iota_client_get_trytes:13][0m
[0;37;40m2020-09-07 07:39:41:json_serializer:  DEBUG: [0m[1;3;32;40m[json_get_trytes_serialize_request:25][0m
[0;37;40m2020-09-07 07:39:41:json_serializer:  DEBUG: [0m[1;3;32;40m[json_get_trytes_deserialize_response:102] {"trytes":["CLMCXMKSJET9EPWKTSNJXAPMDNUGXNKOGIBMHSHACCKNT9SGJOZVEFJAY9GFXMZVMMEO9CGFFSED9AGAWYLRNQQXXUZKLGTGWDIYOA9BASPKRKCEKPJKZOXMEFW9OENZIUJANNDPCUOHWPIUJLWRCMSPUZLMXOZTQQJJIOHFE9MNR9QSLSNWPVNZNZUGQZYZEUG... [0m
[0;30;42m2020-09-07 07:39:41:json_serializer:    ERR: [0m[1;3;32;40m[json_get_trytes_deserialize_response:111] JSON parsing failed[0m
```

**Comment by HowJMay** [comment] 2020-09-17 04:11
Hi @oopsmonk may you take a look about this issue, which causes some trouble to us now

**Comment by oopsmonk** [comment] 2020-09-19 08:52
Can you elaborate on how to reproduce it? how many txs is huge in this case?

**Comment by oopsmonk** [comment] 2021-05-07 07:42
@HowJMay do you have this issue still? may I close this issue focus on the chrysalis network?

**Comment by oopsmonk** [comment] 2021-09-02 05:32
cannot reproduce and is outdated.

**Closed as completed by oopsmonk** 2021-09-02 05:32 UTC
Labels: Type: Bug
